baseURL = 'https://www.kustosz.org/'
languageCode = 'en-us'
title = 'Kustosz'
theme = 'blist'

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = false
[languages]
  [languages.en]
    contentDir = "content"
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Kustosz"
      introSubtitle = "Focus on the worthwhile content with Kustosz, open source self-hosted web application."
      introPhoto = "/picture.jpg"
      logo = "/kustosz_logo.svg"
    [[languages.en.menu.main]]
        name = "About"
        url = "/"
        weight = 1

    [[languages.en.menu.main]]
        name = "Download"
        url = "/download/"
        weight = 2

    [[languages.en.menu.main]]
        name = "Documentation"
        url = "https://docs.kustosz.org/"
        weight = 3

    [[languages.en.menu.main]]
        name = "Changeblog"
        url = "/blog/"
        weight = 4

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true

  # Enable search in header
  enableSearch = false

  # Custom copyright - optional
  copyright = "Copyright © 2022, Mirek Długosz"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-green-100"

[params.homepage.social]
  # Global params common for both languages
  title = "Follow me"
  description = " "
  github = "https://github.com/KustoszApp"

[build]
  writeStats = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
